[package]
name = "mmap-loader"
version = "0.1.0"
edition = "2018"

[profile.release]
codegen-units = 1
debug = false
panic = "abort"
lto = true

[dependencies]
anyhow = "1"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
ntapi = "0.3"
simple_logger = { version = "1.1" }
winapi = { version = "0.3", features = ["impl-default", "fileapi", "handleapi", "memoryapi", "std", "winbase"] }

[dev-dependencies]
serial_test = "0.5"